"""initial schema

Revision ID: cc8bb9a0fe0f
Revises: 
Create Date: 2026-02-23 05:45:14.071227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc8bb9a0fe0f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commodities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_price', sa.Integer(), nullable=False),
    sa.Column('volatility', sa.Integer(), nullable=False),
    sa.Column('illegal', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('config',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discourse_user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('ship_id', sa.Integer(), nullable=True),
    sa.Column('alignment', sa.Integer(), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('turns_remaining', sa.Integer(), nullable=False),
    sa.Column('turns_used_today', sa.Integer(), nullable=False),
    sa.Column('digest_opt_in', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ship_id'], ['ships.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discourse_user_id')
    )
    op.create_table('port_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('ore_mode', sa.String(length=4), nullable=False),
    sa.Column('org_mode', sa.String(length=4), nullable=False),
    sa.Column('equ_mode', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('beacon', sa.Text(), nullable=True),
    sa.Column('is_fedspace', sa.Boolean(), nullable=False),
    sa.Column('nebula', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ship_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('holds', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('max_fighters', sa.Integer(), nullable=False),
    sa.Column('max_shields', sa.Integer(), nullable=False),
    sa.Column('offense', sa.Integer(), nullable=False),
    sa.Column('defense', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('port_type_id', sa.Integer(), nullable=False),
    sa.Column('cash', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['port_type_id'], ['port_types.id'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sector_id')
    )
    op.create_table('sector_warps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_sector_id', sa.Integer(), nullable=False),
    sa.Column('to_sector_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_sector_id'], ['sectors.id'], ),
    sa.ForeignKeyConstraint(['to_sector_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_sector_id', 'to_sector_id', name='uq_sector_warp')
    )
    op.create_index(op.f('ix_sector_warps_from_sector_id'), 'sector_warps', ['from_sector_id'], unique=False)
    op.create_index(op.f('ix_sector_warps_to_sector_id'), 'sector_warps', ['to_sector_id'], unique=False)
    op.create_table('ships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ship_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('fighters', sa.Integer(), nullable=False),
    sa.Column('shields', sa.Integer(), nullable=False),
    sa.Column('hull', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ship_type_id'], ['ship_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('port_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('port_id', sa.Integer(), nullable=False),
    sa.Column('commodity_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('max_quantity', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=4), nullable=False),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ship_cargo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ship_id', sa.Integer(), nullable=False),
    sa.Column('commodity_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ),
    sa.ForeignKeyConstraint(['ship_id'], ['ships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('port_id', sa.Integer(), nullable=False),
    sa.Column('commodity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=4), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_per_unit', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_log')
    op.drop_table('ship_cargo')
    op.drop_table('port_stock')
    op.drop_table('ships')
    op.drop_index(op.f('ix_sector_warps_to_sector_id'), table_name='sector_warps')
    op.drop_index(op.f('ix_sector_warps_from_sector_id'), table_name='sector_warps')
    op.drop_table('sector_warps')
    op.drop_table('ports')
    op.drop_table('ship_types')
    op.drop_table('sectors')
    op.drop_table('port_types')
    op.drop_table('players')
    op.drop_table('config')
    op.drop_table('commodities')
    # ### end Alembic commands ###
